# Generated by Django 6.0.1 on 2026-01-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Master 2 Géographie', max_length=100)),
                ('organisme', models.CharField(help_text='Ex: Coursera, Université de Dakar', max_length=100)),
                ('date_obtention', models.DateField()),
                ('lien_preuve', models.URLField(blank=True, help_text='Lien vers le certificat en ligne', null=True)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='certificats/')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Python, Analyse Spatiale', max_length=50)),
                ('niveau', models.IntegerField(default=80, help_text='Pourcentage de maîtrise (0 à 100)')),
                ('icone_code', models.CharField(blank=True, default='fas fa-check', help_text='Code FontAwesome (ex: fa-brands fa-python)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('PRO', 'Expérience Pro'), ('EDU', 'Formation / Études')], default='PRO', max_length=3)),
                ('poste_ou_diplome', models.CharField(help_text='Titre du poste ou du diplôme', max_length=100)),
                ('structure', models.CharField(help_text='Entreprise ou École', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text="Laisser vide si 'En cours'", null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AlterField(
            model_name='lieu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='outils',
            field=models.CharField(help_text='Ex: Python, Django, QGIS', max_length=200),
        ),
    ]
